flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- llvm-general-3.5.1.0
- llvm-general-pure-3.5.0.0
- mtl-2.2.1
- optparse-applicative-0.12.0.0
- parsec-3.1.9
- primitive-0.6.1.0
- setenv-0.1.1.3
- text-1.2.1.3
- transformers-compat-0.4.0.4
- utf8-string-1.0.1.1
- vector-0.11.0.0
- word8-0.1.2
resolver: ghc-7.10.1
